# Generated by Django 4.1.2 on 2022-10-23 21:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_posts_post_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='img'),
        ),
    ]
